name: terraform
run-name: ${{ github.actor }} is terraforming
on: [push]
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Install the terraform dependency packages
        run: sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
      
      - name: Install the HashiCorp GPG key
        run: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      
      - name: Verify the key's fingerprint
        run: gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
      
      - name: Add the official HashiCorp repository to your system
        run: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      
      - name: Download the package information from HashiCorp
        run: sudo apt update
        
      - name: Install Terraform from the new repository
        run: sudo apt-get install terraform
        
      - name: Clone this repo
        run: git clone https://github.com/FajarMaftuhFadli/my-terraform.git .
        
      - name: Set environment variable for GCP authentication
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS" > $GITHUB_ENV
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      #- name: Authenticate with GCP using service account
      #  run: |
      #    gcloud auth application-default login
      #    echo "Enter the authorization code from the browser window:"
      #    read auth_code
      #    echo $auth_code | gcloud auth application-default print-access-token

      - name: Initialize terraform
        run: terraform init
      
      - run: terraform plan
